// app/layout.js (o app/root-layout.js si es necesario)

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Fuentes de Google (Geist y Geist_Mono)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        {/* Agrega el enlace a Google Fonts para Noto Sans */}
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-moderat`}
      >
        {children}
      </body>
    </html>
  );
}
